# -*- coding: utf-8 -*-
"""step 2.1) Combine Mean data together

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zQiJqgIndTTF7IGfVqBGJA8Hmn45-YbY
"""

import pandas as pd
import os
from google.colab import files

!pip install openpyxl

folder_path1 = 'Data1'
folder_path2 = 'Data2'
folder_path3 = 'Data3'

def merge_excel(filepath, new_filepath):
  all_data = []
  for file in os.listdir(filepath):
    if file.endswith('.xlsx') or file.endswith('.xls'):
      try:
        excel_file = os.path.join(filepath, file)
        df = pd.read_excel(excel_file)
        all_data.append(df)
      except Exception as e:
        print(f"Error reading file {file}: {e}")

  if all_data:
    merged_df = pd.concat(all_data, ignore_index=True)
    merged_df.to_excel(new_filepath, index=False)
    print(f"Successfully merged data to {new_filepath}")
  else:
    print(f"No Excel files found in {filepath}")

merge_excel(folder_path1, 'merged_data1.xlsx')
merge_excel(folder_path2, 'merged_data2.xlsx')
merge_excel(folder_path3, 'merged_data3.xlsx')

files.download('merged_data1.xlsx')
files.download('merged_data2.xlsx')
files.download('merged_data3.xlsx')